version: '3'
services:
  server:
    build: ./env/server
    ports:
    - 9050:9050
    depends_on:
    - redis
    volumes:
    - ./code:/code
    networks:
    - decluster_network
  redis:
    image: 'bitnami/redis:latest'
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
networks:
  decluster_network:
    external: true
